--require("filetype").setup {
--    overrides = {
--        extensions = {
--            tf = "terraform",
--            tfvars = "terraform",
--            tfstate = "json",
--        },
--    complex = {
--          -- Set the filetype of any full filename matching the regex to gitconfig
--          [".*i3/config"] = "i3config", -- Included in the plugin
--          ["*lambda*/serverless.template"] = "json", -- Included in the plugin
--          }
--        },
-- }
